Task/accidents node aggregation
StaszekM/gradient pull request #25
Opened 2024-03-15 04:59 UTC by gry-mar

Moduł do agregacji wypadków z analizą i użyciem w dedykowanym notebooku
- cechy wierzchołków z OSMNx
- agregacja na podstawie obszaru aż nie zagreguje się wszystkich wypadków

2024-03-18 19:47 UTC, JuliaJ194 commented on src/graph/create_osmnx_graph.py
> +    # def graph_visualization(self):
to ma zostać?

2024-03-18 19:47 UTC, JuliaJ194 commented on src/graph/create_osmnx_graph.py
> +    def show_statistics(self):
moze by to zwracać jako np słownik? żeby później moc uwyprintowac w notebooku albo logować w wandb

2024-03-18 20:12 UTC, JuliaJ194 commented on src/graph/create_osmnx_graph.py
> +    # def graph_visualization(self):
też można zwracać jako fig

2024-03-19 07:12 UTC, gry-mar commented on src/graph/create_osmnx_graph.py
> +    def show_statistics(self):
można, zmienię to

2024-03-19 07:15 UTC, gry-mar commented on src/graph/create_osmnx_graph.py
> +    # def graph_visualization(self):
właśnie nie wiedziałam co zrobić z tą wizualizacją tak szczerze, bo sam plot trochę długo leci. chyba lepiej byłoby zwrócić po prostu graf NX i w utilsach do wizualizacji już zrobić metody wizualizacji, łatwiej będzie później decydować w jaki sposób wgl to prezentować. co myślisz?

2024-03-19 08:18 UTC, JuliaJ194 commented on src/graph/create_osmnx_graph.py
> +    def show_statistics(self):
mogę zmienić, bo do wandb tez mi sie przyda

2024-03-19 08:39 UTC, gry-mar commented on src/graph/create_osmnx_graph.py
> +    def show_statistics(self):
okej, to ja to zostawiam w takim razie

2024-03-21 12:35 UTC, JuliaJ194 commented on src/graph/create_graph.py
> -        print(
dupa

2024-03-21 18:43 UTC, StaszekM requested changes

2024-03-21 18:43 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +class OSMnxGraph:
udokumentuj w tej klasie te funkcje, opisz pokrótce jak dzialają, ciężko zrozumieć co się tu dzieje a to są nietrywialne algorytmy i każdy musi bez wczytywania się w kod rozumieć, to przyspieszy pracę i używanie

sam w PR tutaj proponuję format docstringa wg NumPy: https://github.com/StaszekM/gradient/pull/26

Dlaczego NumPy? Bo moim zdaniem wygląda bardziej zrozumiale niż Google docstring czy inne formaty, NumPy i inne scientific biblioteki lubią to, a do tego współpracuje ze Sphinx więc gdy będziemy kiedyś chcieli zrobić profesjonalną stronkę do dokumentacji taką jaką mają Pandas czy ScikitLearn, to będzie łatwe

Jest gotowa wtyczka do VScode która generuje docstringi: https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring

Materiały dotyczącye NumPy docstring:
https://numpydoc.readthedocs.io/en/latest/format.html
https://www.datacamp.com/tutorial/docstrings-python

2024-03-21 18:43 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +            accident_point = accident.geometry
myślę że tworzenie boxa i szukanie elementów wewnątrz box niepotrzebnie się duplikuje. Spróbuj może zrobić to w jednej pętli while z breakiem? myślę że będzie spoko

zwróć uwagę że pierwsze odpalenie tej logiki przed while niewiele się różni od kolejnych odpaleń wewnątrz while, może tylko że wzrasta width boxa

2024-03-21 18:43 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +    def _get_lat_lon_distance(self, lat, lon, meters):
z reguły kolejność deklaracji jest taka:

1. konstruktor
2. metody publiczne
3. metody prywatne z _

Prywatne nie zawsze interesują developera i dlatego lądują na dole

2024-03-21 18:43 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +    def _aggregate_accidents(self, aggregation_type:str):
jak oceniasz szybkość tej funkcji? pytam bo widzę sporo for, while, a także niskopoziomowe funkcje na shapely

2024-03-21 18:43 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +    def create_graph(self, aggregation_type):
aggregation type to chyba będzie union jakby co

2024-03-21 18:43 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +            distance = cdist([accident_point], [node])
w tym cdist da się może wyliczyć wszystkie odległości parami naraz? bo tutaj robisz to element po elemencie, a w dokumentacji widzę że można robić to na całych arrayach

2024-03-21 18:43 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +    def _get_edge_attrs(self):
może wybierz jedną z opcji nazewnicwa, tj attrs or features?

2024-03-22 00:49 UTC, gry-mar commented on src/graph/create_osmnx_graph.py
> +    def create_graph(self, aggregation_type):
nie rozumiem

2024-03-22 00:51 UTC, gry-mar commented on src/graph/create_osmnx_graph.py
> +            accident_point = accident.geometry
To jak proponujesz to rozwiązać? bo szczerze mówiąc nie mam pomysłu

2024-04-09 22:15 UTC, gry-mar commented
@StaszekM możesz sprawdzić czy ok

2024-04-10 20:00 UTC, StaszekM requested changes

2024-04-10 20:00 UTC, StaszekM commented on notebooks/osmnx_graph_train_test.ipynb
W tym notebooku trzeba dopisać w markdown poszczególne fazy i co się dzieje, bo czytanie kodu ujawnia tylko co jest robione, a nie ujawnia *po co* - wiem że w niektórych miejscach to zrobiłaś, ale nie we wszystkich, np przygotowywanie modelu, trening, ewaluacja

dodatkowo usuń outputy z pytorch lightninga bo to są setki linijek i zostają w gicie

2024-04-10 20:00 UTC, StaszekM commented on notebooks/osmnx_graph_train_test.ipynb
Widzę kilka razy kawałki kodu z nazwami zmiennych typu X2, gdf2 - zmień proszę nazwy na bardziej deskryptywne

importy wewnątrz jakichś komórek niżej przerzuć do góry żeby trzymać się naszych ustaleń

2024-04-10 20:00 UTC, StaszekM commented on notebooks/osmnx_graph_train_test.ipynb
usuń wszystkie komórki które pokazują jakieś outputy, które nie są niezbędne - rozumiem że sobie używałaś tych komórek żeby sprawdzać różne rzeczy po drodze, ale tu są niepotrzebne i utrudniają śledzenie wątku

2024-04-10 20:00 UTC, StaszekM commented on src/baseline_models/GCN/supervised_node_classification.py
> +        print(f"loss: {loss.item()}")
po co ten print? linijkę wyżej loguje się do loggera

2024-04-10 20:00 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +            pd.DataFrame: cleaned dataframe that contains node features
na czym polega słowo 'cleaned'? jaki 'cleaning' jest robiony?

2024-04-10 20:00 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +            pd.DataFrame: cleaned DataFrame that contains edge features
jw. cleaning ?

2024-04-10 20:00 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +        """Method that gets edge attributes.
tu zdecydowanie musisz opisać więcej rzeczy które nie wynikają prosto z nazwy funkcji, to że to jest geter na edge attrs to już wiemy xdd

2024-04-10 20:00 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +        """Finds nearest node
...nearest node from given accident point

2024-04-10 20:00 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +        """Finds nearest edge
...nearest edge from given accident point

2024-04-10 20:00 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +            accident_point = accident.geometry
to zostawmy jak jest

2024-04-10 20:00 UTC, StaszekM commented on src/graph/create_osmnx_graph.py
> +        """Method that gets edge attributes.
sory za mansplaining albo jeśli mówię ci coś co już wiesz, ale dobre komentarze tłumaczą tak, by człowiek bez patrzenia w kod wiedział, jak tego użyć, co zostanie zwrócone i co się stanie po drodze

2024-04-10 20:00 UTC, StaszekM commented on .DS_Store
co to?

2024-04-10 22:25 UTC, gry-mar commented on notebooks/osmnx_graph_train_test.ipynb
spoko, w sumie traktowałam ten notebook bardziej roboczo ale no widzę że to bez sensu

2024-04-10 22:26 UTC, gry-mar commented on src/baseline_models/GCN/supervised_node_classification.py
> +        print(f"loss: {loss.item()}")
no żeby sobie testowo zobaczyć ale usunę

2024-04-10 22:27 UTC, gry-mar commented on .DS_Store
ah jakieś macowe coś chyba, pierwszy raz w sumie pracowałam na gradiencie na macu i się musiało dodać, dam do .gitignore

2024-04-11 13:23 UTC, merged